### PR TITLE
Fixes #49

### LINKED ISSUE #49: Error I created while implementing auto-continue
I didn't realise that the popup wasn't created until displayed so I'm fixing the error which displays when it is not created but the scripts try to access it.
I'll fix it and create a PR right away

### PR DESCRIPTION
**Pull request by erwan-fb**
Better when included in the issue

### CODE REVIEW

**Comment by erwan-fb** [comment]
nwm. Next time i'll do it correctly

**Comment by erwan-fb** [comment]
might modify it a little bit to be sure the selected button from the array is the correct one

**Comment by proffapt** [comment]
is the work done?

**Comment by erwan-fb** [comment]
Not yet because to popup isn't easy to catch but should be done today

**Comment by erwan-fb** [comment]
should be alright, I need to test it one more time before to make sure it is working as intended.

**Comment by proffapt** [comment]
tell me whenever it's done, so i can verify and merge

**Comment by erwan-fb** [comment]
Seems almost done to me. I'll verify later today and correct if needed

**Comment by erwan-fb** [comment]
Totally works this time, you can verify and merge

**Comment by proffapt** [comment]
share screenshots or screencast

**Review by proffapt — APPROVED** [review]
LGTM

**Pull request merged**
