### PR TITLE
Updated manifest from v2 to v3, issue#2

### PR DESCRIPTION
**Pull request by Alph3ga**
Updated manifest and checked working of most features

### CODE REVIEW

**Review by proffapt — CHANGES_REQUESTED** [review]
Changing manifest version, just this won't help;
Did the extension even compiled or did you even test it?
Read about what's the difference in manifest 2 & 3 and why one code will not work for other version.

**Comment by Alph3ga** [comment]
I have made changes in the manifest to comply with V3 standards, like having separate host_permissions, actions instead of browser_actions, etc. I did not find any significant changes required, to my knowledge, this doesn't look like it uses background pages, or the action/tabs API. 
I have tested most of the features of the extension, seems to run fine with updated manifest.

**Comment by proffapt** [comment]
> I have made changes in the manifest to comply with V3 standards, like having separate host_permissions, actions instead of browser_actions, etc. I did not find any significant changes required, to my knowledge, this doesn't look like it uses background pages, or the action/tabs API. 
> I have tested most of the features of the extension, seems to run fine with updated manifest.

Well sounds good to me if you have tested, wait till i get my rig setup; will be done by tonight let's see tomorrow.

**Comment by proffapt** [comment]
If you have checked all the features then it looks good to me; unfortunately I can't test now (my device is not capable of it). I will merge the PR as it is not something which will break the extension and you tested it.

**Pull request merged**
