### PR TITLE
Changed ui of chrome and firefox version

### PR DESCRIPTION
**Pull request by himanishu-2512**
I have done changes in the UI of chrome version.

### CODE REVIEW

**Review by proffapt — CHANGES_REQUESTED** [review]
The UI looks pretty decent and neat - better than before!

Some changes needed:
1. There are actually three modes - dark, light and system - your changes are actually good for dark and light but they break in the system mode. Fix them.
    image
2. Color scheme is good - there is one more thing in my mind. What I wanted is Div enclosed in rectangular border closed / hidden by default; currently it's open. And when the user wants to open the particular section it expands sliding every other stuff down. This will make the extension less cluttered.
3. For firefox UI you can literally replace the files in firefox folder with those in chrome folder which you modified.

**Review by proffapt — APPROVED** [review]
Current status:

1. So the `system` mode UI is fixed.
2. Firefox and Chrome builds are in sync
3. Things are hidden by default

**Comment by proffapt** [comment]
@himanishu-2512 the only thing left is making the closed format a bit more attractive.
Currently it looks so-empty - No you don't have to reduce the size.
Come up with something which can fill the space.

- You might make a border around the collapsed options
- and expand the border / box also when the option is expanded
Currently it's only on two sides
image

Or maybe feel free to implement something else you have in your mind. Ideas are well appreciated.. better to share the design a rough one would work and then implement in code.

When something is implemented for this part, this PR will be ready to Merge!

PS: consider joining the slack channel for better contact

**Comment by himanishu-2512** [comment]
This is the ui for dark theme 
image
image
UI for light theme
image
image

**Comment by proffapt** [comment]
@himanishu-2512 , I see you have directly changed the UI. This is exactly what I wanted - great job!

Few changes might be needed:
- Make drop down arrows a bit bigger
- The checks/ticks don't seem to be aligned inside the boxes

Before doing that, push the code to your branch so that I can see the UI once on my system

**Comment by himanishu-2512** [comment]
@proffapt I have pushed the code please review it and let me know if there any more further changes excluding the above ones.

**Review by proffapt — CHANGES_REQUESTED** [review]
First of all, the implementation is nice; kudos to you!

Few changes needed:

- [x] Change to `toggle` input options instead of checkboxes
- [x] Increase the indentation by 50% to what it is currently.
   image
- [x] Decrease the height of the `youtube history` button.
- [x] Remove the space between the last entry and that button, there can be multiple ways choose whatever looks good to you.
   image

PS: The first point was updated.

**Comment by proffapt** [comment]
> Few changes needed:
> 
>     * The checks/ticks don't seem to be aligned inside the boxes

Umm, I just thought what about having `toggle` instead of checkboxes, that would make more sense


And what a timing, was just writing this message and saw you made some changes. XD

**Comment by himanishu-2512** [comment]
> > Few changes needed:
> > ```
> > * The checks/ticks don't seem to be aligned inside the boxes
> > ```
> 
> Umm, I just thought what about having `toggle` instead of checkboxes, that would make more sense
> 
> And what a timing, was just writing this message and saw you made some changes. XD

Yeah! we can do so.

**Comment by proffapt** [comment]
> Yeah! we can do so

Great! 
And also look at the updated review as well: https://github.com/proffapt/own-youtube/pull/31#pullrequestreview-1223934967

**Comment by himanishu-2512** [comment]
> First of all, the implementation is nice; kudos to you!
> 
> Few changes needed:
> 
> * [X]  Change to `toggle` input options instead of checkboxes
> * [X]  Increase the indentation by 50% to what it is currently.
>   image
> * [X]  Decrease the height of the `youtube history` button.
> * [X]  Remove the space between the last entry and that button, there can be multiple ways choose whatever looks good to you.
>   image
> 
> PS: The first point was updated.

@proffapt  solved all the above issues.

**Review by proffapt — APPROVED** [review]
LGTM. finally.

**Comment by proffapt** [comment]
- Indent this last section as well. 
- And some better looks of the radio buttons.

image

**Comment by himanishu-2512** [comment]
> * Indent this last section as well.
> * And some better looks of the radio buttons.
> 
> image

Oops ! I forgot about the last section. Considering it also for the toggle input rather than a radio button. Isn't  it a good idea?

**Comment by proffapt** [comment]
> > * Indent this last section as well.
> > * And some better looks of the radio buttons.
> > 
> > image
> 
> Oops ! I forgot about the last section. Considering it also for the toggle input rather than a radio button. Isn't it a good idea?

Not exactly because the user will be choosing either one of them so here comes the play of radio buttons.. toggle will be too much for this

**Comment by proffapt** [comment]
@himanishu-2512 resolve the above suggestion so that this PR can be merged.

**Comment by himanishu-2512** [comment]
> @himanishu-2512 resolve the above suggestion so that this PR can be merged.

@proffapt  done!

**Review by proffapt — APPROVED** [review]
LGTM.

**Pull request merged**
