### PR TITLE
Auto continue

### PR DESCRIPTION
**Pull request by erwan-fb**
Clicks on the yes on the popup that appears after a while watching without having interactions with the site.
This little modification prevents this popup from ruining your day when you are working and suddenly the musics stop.

### CODE REVIEW

**Comment by proffapt** [comment]
Shouldn't this be an option selected by the user, whether to autoplay or not?

**Comment by erwan-fb** [comment]
Ok I'll do that.
Edit: it is just the removal of an annoying popup but if you want a option for it, it is you choice

**Comment by erwan-fb** [comment]
Option for user made

**Review by proffapt — APPROVED** [review]
LGTM

**Pull request merged**
